language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
  - build_platform kytelabs:avr:bleduino
branches:
  only:
    - gh-pages
notifications:
  email:
    on_success: change
    on_failure: change